#!/bin/bash
# post-setup.sh — Runs before initramfs generation
# $1 = ROOTFS path (passed by mklive)
# VOID_ISO_MODE = "desktop" | "server" (set by wrapper)

ROOTFS="$1"
MODE="${VOID_ISO_MODE:-desktop}"

echo "=== Custom Void Linux Setup (${MODE}) ==="
echo "ROOTFS: $ROOTFS"


# ─────────────────────────────────────────
#  Desktop only: greetd on tty1
# ─────────────────────────────────────────

if [ "$MODE" = "desktop" ]; then
    echo ""
    echo "=== [desktop] Configuring greetd on tty1 ==="

    chroot "$ROOTFS" useradd \
        --system --no-create-home --shell /sbin/nologin \
        greeter 2>/dev/null \
        && echo "  Created greeter user." \
        || echo "  greeter user already exists."

    AGETTY_TTY1="$ROOTFS/var/service/agetty-tty1"
    if [ -L "$AGETTY_TTY1" ]; then
        rm "$AGETTY_TTY1"
        echo "  Disabled agetty-tty1."
    fi

    GREETD_SV="$ROOTFS/etc/sv/greetd"
    GREETD_LINK="$ROOTFS/var/service/greetd"
    if [ -d "$GREETD_SV" ] && [ ! -L "$GREETD_LINK" ]; then
        ln -s /etc/sv/greetd "$GREETD_LINK"
        echo "  Enabled greetd on tty1."
    elif [ ! -d "$GREETD_SV" ]; then
        echo "  ERROR: $GREETD_SV not found — is greetd installed?"
        exit 1
    fi
fi


# ─────────────────────────────────────────
#  kmscon — tty2 (desktop) or tty1 (server)
# ─────────────────────────────────────────

if [ "$MODE" = "desktop" ]; then
    KMSCON_VT=2
    AGETTY_DISABLE="$ROOTFS/var/service/agetty-tty2"
else
    KMSCON_VT=1
    AGETTY_DISABLE="$ROOTFS/var/service/agetty-tty1"
fi

echo ""
echo "=== Configuring kmscon on tty${KMSCON_VT} ==="

KMSCON_SV="$ROOTFS/etc/sv/kmscon"
KMSCON_RUN="$KMSCON_SV/run"

# Write the run script with the correct VT for this mode.
# This overwrites whatever custom-files/-I copied in.
mkdir -p "$KMSCON_SV"
cat > "$KMSCON_RUN" <<EOF
#!/bin/sh
# kmscon on tty${KMSCON_VT} — generated by post-setup.sh (${MODE} mode)
exec kmscon --vt=${KMSCON_VT} 2>&1
EOF
chmod +x "$KMSCON_RUN"
echo "  Wrote kmscon run script (--vt=${KMSCON_VT})."

# Disable agetty on the VT kmscon will occupy
if [ -L "$AGETTY_DISABLE" ]; then
    rm "$AGETTY_DISABLE"
    echo "  Disabled agetty on tty${KMSCON_VT}."
fi

# Enable the kmscon service
KMSCON_LINK="$ROOTFS/var/service/kmscon"
if [ ! -L "$KMSCON_LINK" ] && [ -d "$KMSCON_SV" ]; then
    ln -s /etc/sv/kmscon "$KMSCON_LINK"
    echo "  Enabled kmscon."
fi


# ─────────────────────────────────────────
#  Server: remove desktop-only config files
#  (custom-files/-I copies everything; clean
#   up what doesn't belong on a server)
# ─────────────────────────────────────────

if [ "$MODE" = "server" ]; then
    echo ""
    echo "=== [server] Removing desktop config files ==="
    rm -rf "$ROOTFS/etc/greetd"
    echo "  Removed /etc/greetd/."
fi


# ─────────────────────────────────────────
#  Fish as default shell for new users
# ─────────────────────────────────────────

echo ""
echo "=== Setting fish as default shell ==="

USERADD_DEFAULTS="$ROOTFS/etc/default/useradd"
if [ -f "$USERADD_DEFAULTS" ]; then
    sed -i 's|^SHELL=.*|SHELL=/usr/bin/fish|' "$USERADD_DEFAULTS"
    echo "  Updated SHELL in $USERADD_DEFAULTS."
else
    echo "SHELL=/usr/bin/fish" >> "$USERADD_DEFAULTS"
    echo "  Created $USERADD_DEFAULTS."
fi


# ─────────────────────────────────────────
#  update-odin
# ─────────────────────────────────────────

echo ""
echo "=== Configuring update-odin ==="

UPDATE_ODIN="$ROOTFS/opt/update-odin"
if [ -f "$UPDATE_ODIN" ]; then
    chmod +x "$UPDATE_ODIN"
    echo "  Set +x on $UPDATE_ODIN."
else
    echo "  WARNING: $UPDATE_ODIN not found — skipping."
fi


echo ""
echo "=== Done (${MODE}) ==="
